### ISSUE TITLE
Add emoji/fan marks to list views?

### ISSUE THREAD

**Issue by danirukun** [holodata/raycast-holodex#1]
It can be helpful as a visual aid in distinguishing different channels. At the moment the Holodex API does not serve fan marks, so the mapping has to be done on the client-side at the moment (similar to how I do it here: https://github.com/DaniruKun/hololive-menubar-plugin/blob/master/hololive.5m.rb#L133)

**Comment by uetchy** [comment]
<img width="1005" alt="Screen Shot 2022-04-15 at 2 38 32" src="https://user-images.githubusercontent.com/431808/163443681-d573f123-1ff2-4a4b-850a-3a7b33a29f8a.png">

Trying out List.Item.Detail component that was introduced in the latest Raycast API. It can keep the list incredibly clean and make it much easier to navigate around.

**Comment by danirukun** [comment]
Looks even better!

**Comment by uetchy** [comment]
Ok pushed the changes. Can we assume this issue has been resolved?

**Comment by danirukun** [comment]
Yup, let's close it.
